version: '3.5'

services:
  store:
    image: postgres
    environment:
      POSTGRES_USER: company
      POSTGRES_PASSWORD: company-pass
      POSTGRES_DB: companies
    ports:
      - "5432:5432"
    networks:
      - companies

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - companies
  broker:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "19092:9092"
    networks:
      - companies
  companies:
    image: companies
    depends_on:
      - store
      - broker
    environment:
      ENV: local
      JWT_SIGNING_KEY: secret

      DB_HOST: store
      DB_USER: company
      DB_PASSWORD: company-pass
      DB_NAME: companies

      KAFKA_HOST: broker:9092
      KAFKA_TOPIC: companies
      KAFKA_PARTITION: 0
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - companies
networks:
  companies:
    driver: bridge